# This file was generated by GoReleaser. DO NOT EDIT.
cask "l4" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7c32df953fc66efbb1d7c75c45b65750c2708e1e28959eb11e97bb2fdd6320ac"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "20c24481fddf204fbaec94578d0ef2666da2f730eff198c19f05145e285ea7ce"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6c69b364fa8c1b8b645ebfab414ba6994c65ea2d791345118989283670515b5"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83fc0b1c8c823b4728f7f5113d1340b62742c84834e5c0ee5b7b7176ff48a99a"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "l4"
  desc "LevelFour CLI (short alias): cloud cost optimization from the terminal"
  homepage "https://levelfour.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "l4"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/l4"]
    end
  end

  # No zap stanza required

end
