# This file was generated by GoReleaser. DO NOT EDIT.
cask "levelfour" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "28d85de12565be791e8c17759c0d82febe4d5732c4f84fa7609fe9b4af8363b6"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5cb12561ed743aa09b6215216850711edcfd4b2c68a3424f5bf1d81f493ff5df"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fed38f5ac2922125ddf8f24aeac2e93d75ff40d6c1c33f5590bda1d0df6c96ec"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89841574c296cf042b0817b88c4beaf284b7fb003fc57a1679f9e238b649a10c"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "levelfour"
  desc "LevelFour CLI: cloud cost optimization from the terminal"
  homepage "https://levelfour.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "levelfour"
  binary "l4"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/levelfour"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/l4"]
    end
  end

  # No zap stanza required
end
