# This file was generated by GoReleaser. DO NOT EDIT.
cask "levelfour" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "969a8d3478441628c9696a6963a04b8c677e84e2cd99b297a04156d82e3ee36f"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b41eeac3aa8b2957dc448e221facb1ca586a1dcd6a164544db030c91cc8503f2"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5249c9a70f781868d9a5c603a8c9786f831847b8d6835edbb803e8946bd39fd2"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d43f07443c02221e3ed22077e99fff30bcf729480290c87e2578b27528a68a21"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "levelfour"
  desc "LevelFour CLI: cloud cost optimization from the terminal"
  homepage "https://levelfour.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "levelfour"
  binary "l4"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/levelfour"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/l4"]
    end
  end

  # No zap stanza required

end
