# This file was generated by GoReleaser. DO NOT EDIT.
cask "levelfour" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "db7560774d5866a7073a5416be3960ade123bf4ea595600cae9384cef1414ae0"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f49cdfdb1acf2111f037a038ea4f6fe0b3ad9adb81b25da1bd1523253d2a9e6"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff8d6c23c24f1c3b40bda06d51b75809e6157dfb7ca6fa9881e997de2a0a4f58"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f7c0d7916aa915835853d6feecabbe52d55dbab14c80ce254f73afa8cb2e93f1"
      url "https://github.com/LevelFourAI/levelfour-cli/releases/download/v#{version}/levelfour-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "levelfour"
  desc "LevelFour CLI: cloud cost optimization from the terminal"
  homepage "https://levelfour.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "levelfour"
  binary "l4"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/levelfour"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/l4"]
    end
  end

  # No zap stanza required
end
